


export enum AuthRPC {
    LOGIN = "LOGIN",
    SIGNUP = "SIGNUP",
    UPGRADE_ACCOUNT = "UPGRADE_ACCOUNT",
}

export enum UserRPC {
    GET_USER_BY_ID = "GET_USER_BY_ID",
    GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL",
    CREATE_USER = "CREATE_USER",
    UPDATE_USER_BY_ID = "UPDATE_USER_BY_ID",
}

export enum KYCRPC {
    GET_KYC_BY_ID = "GET_KYC_BY_ID",
    CREATE_KYC = "CREATE_KYC",
}

export enum AccountRPC {
    UPGRADE_ACCOUNT = "GET_ACCOUNT_BY_ID",
    GET_ACCOUNT_BY_USER_ID = "GET_ACCOUNT_BY_USER_ID",
    CREATE_ACCOUNT = "CREATE_ACCOUNT",
    UPDATE_ACCOUNT_BY_ID = "UPDATE_ACCOUNT_BY_ID",
}

export enum TransactionRPC {
    CREATE_TRANSACTION = "CREATE_TRANSACTION",
    GET_TRANSACTION_BY_ID = "GET_TRANSACTION_BY_ID",
    GET_TRANSACTION_BY_ACCOUNT_ID = "GET_TRANSACTION_BY_ACCOUNT_ID"
}

export enum BusinessRPC {
    GET_BUSINESS_BY_ID = "GET_BUSINESS_BY_ID",
    CREATE_BUSINESS = "CREATE_BUSINESS",
    UPDATE_BUSINESS = "UPDATE_BUSINESS",
    DELETE_BUSINESS = "DELETE_BUSINESS",
}

export type RPC_QUEUE_TYPE =  "auth" |  "user" | "account" | "security" | "compliance" | "business" | "kyc" | "transaction";
